// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmykafF7Q0PwIpcpdXbj_Ii4l5WvP7vs',
    appId: '1:504791388713:web:25fc02f34fbd69cd13c238',
    messagingSenderId: '504791388713',
    projectId: 'fire-base-finanacenew',
    authDomain: 'fire-base-finanacenew.firebaseapp.com',
    storageBucket: 'fire-base-finanacenew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnn0GkYO0vqSslzf8yL57NxFpFznb9zTk',
    appId: '1:504791388713:android:9cd2b79d760f515313c238',
    messagingSenderId: '504791388713',
    projectId: 'fire-base-finanacenew',
    storageBucket: 'fire-base-finanacenew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0heuzojyGvDYbSyEjDrDU-sCc_mXwFVw',
    appId: '1:504791388713:ios:d17315e3bddb329c13c238',
    messagingSenderId: '504791388713',
    projectId: 'fire-base-finanacenew',
    storageBucket: 'fire-base-finanacenew.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0heuzojyGvDYbSyEjDrDU-sCc_mXwFVw',
    appId: '1:504791388713:ios:d17315e3bddb329c13c238',
    messagingSenderId: '504791388713',
    projectId: 'fire-base-finanacenew',
    storageBucket: 'fire-base-finanacenew.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJmykafF7Q0PwIpcpdXbj_Ii4l5WvP7vs',
    appId: '1:504791388713:web:b91893722186a0ec13c238',
    messagingSenderId: '504791388713',
    projectId: 'fire-base-finanacenew',
    authDomain: 'fire-base-finanacenew.firebaseapp.com',
    storageBucket: 'fire-base-finanacenew.appspot.com',
  );

}